### ISSUE TITLE
Error: Access not granted or expired. (line 421, archive "Service", project "OAuth2")

### ISSUE THREAD

**Issue by leticiafatimaa** [gsuitedevs/apps-script-oauth2#152] opened 2018-10-02 17:55 UTC
I am using the [SignaturesManager for Google Apps Script](https://github.com/abdonrd/appsscript-signaturesmanager/blob/master/README.md), which uses your library to do the authentication. But when I make the request, this message appears to me: **Error: Access not granted or expired. (line 421, archive "Service", project "OAuth2")**

**Comment by erickoledadevrel** [comment] 2018-10-02 18:14
You'll have to file an issue with them directly, as there is no way to know the cause of the problem based solely on that error message. I'll need to have one of their developers look at the problem and they can reach out to me if they find a bug,

**Comment by erickoledadevrel** [comment] 2018-10-02 18:17
My apologies, it looks like they actually have you use the library directly, and just hand them an authenticated service. Have you revoked the script's access to your access to your account? Can you check that you have a `refresh_token` stored in your user properties?

**Comment by leticiafatimaa** [comment] 2018-10-02 18:17
But the problem is pointing to your library and not to them.

**Comment by leticiafatimaa** [comment] 2018-10-02 18:33
I'm a beginner on this subject, and if you can help me, I'll be grateful. My code is like this:

```
function getSignaturesService() {
  return OAuth2.createService('signatures')
  .setAuthorizationBaseUrl('https://accounts.google.com/o/oauth2/auth')
  .setTokenUrl('https://accounts.google.com/o/oauth2/token')  
  
  .setClientId('105726fake595-b155trvuajpfake43j0kd7gn25giuj.apps.googleusercontent.com')
  .setClientSecret('PFQBfakeKbJLOcic_hZ0W')
  
  .setCallbackFunction('authCallback')
  
  .setParam('state', getStateToken('authCallback'))
  .setPropertyStore(PropertiesService.getUserProperties())
  
  .setScope('https://apps-apis.google.com/a/feeds/emailsettings/2.0/')
  
  .setParam('login_hint', Session.getActiveUser().getEmail())
  .setParam('access_type', 'offline');
  
}

function showAuthorization() {
     var signaturesService = getSignaturesService();

    if (!signaturesService.hasAccess()) {
        var authorizationUrl = signaturesService.getAuthorizationUrl();
            template = HtmlService.createTemplate(
            '<a href="<?= authorizationUrl ?>" target="_blank">Authorize</a>. ' +
            'Refresh the page when the authorization is complete.');

        template.authorizationUrl = authorizationUrl;

        return template.evaluate().setSandboxMode(HtmlService.SandboxMode.IFRAME);
    } else {
        Logger.log("...")
    }
}

function authCallback(request) {
    var signaturesService = getSignaturesService(),
        isAuthorized = signaturesService.handleCallback(request);

    if (isAuthorized) {
        return HtmlService.createHtmlOutput('Success! You can close this tab.');
    }

    return HtmlService.createHtmlOutput('Denied. You can close this tab.');
}

function getStateToken(callbackFunction){
  var stateToken = ScriptApp.newStateToken()
     .withMethod(callbackFunction)
     .withTimeout(120)
     .createToken();
 return stateToken;
}

function updateEmailSignature() {
  var html = "signature"
  
  var response = UrlFetchApp.fetch('https://www.googleapis.com/gmail/v1/users/leticia@domain.com.br/settings/sendAs/leticia@domain.com.br', {
    method: "PUT",
    muteHttpExceptions: true,
    contentType: "application/json",
    payload: createPayload_(html),
    headers: {
      Authorization: 'Bearer ' + getSignaturesService().getAccessToken()
    }    
  });
  
  if (response.getResponseCode() !== 200) {
    Logger.log("ERROR: " + response.getContentText());
  } else {
    Logger.log("Signature updated");
  }
   
}
```

I was reading the closed issues and I found several people with this same problem, however, there was one that commented about recovering the token and made the code available, I put the function `getStateToken(callbackFunction)`  but there was no change.

**Comment by leticiafatimaa** [comment] 2018-10-02 18:38
The script is authorized in my account.

**Comment by erickoledadevrel** [comment] 2018-10-02 18:45
I'd suggest adding the following line to your service config:

```js
.setParam('prompt', 'consent')
```

And then re-run the `showAuthorization()` function.

**Comment by leticiafatimaa** [comment] 2018-10-02 18:47
I added and executed, but nothing happened.

**Comment by erickoledadevrel** [comment] 2018-10-02 18:51
Sorry, it looks like your `showAuthorization()` method expects it to be called by some other method to show the HTML in a dialog or sidebar. At this point your best bet may be to adapt the code in this repo's `README` to your needs, since it expects to be run in the script editor.

Closing this issue since it seems clear that the error message is accurate, since you haven't obtained authorization yet.

**Closed by erickoledadevrel** 2018-10-02 18:51 UTC

**Comment by leticiafatimaa** [comment] 2018-10-02 20:09
Hello, I was able to make `showAuthorization()` work, but it still gives the same error message.
