### ISSUE TITLE
"JSON: SyntaxError: Unexpected token:" for Gmail add-on

### ISSUE THREAD

**Issue by ShovelHand** [gsuitedevs/apps-script-oauth2#185] opened 2019-06-05 00:58 UTC
Pardon me; I'm not sure where I've gone wrong here.
I'm running an OAuth authentication server on my local machine accessed through ngrok. 

I've defined my my OAuth service like this:
```javascript
function getOAuthService() {
  userProperties = PropertiesService.getUserProperties();

  return OAuth2.createService('IntegrationService')
      .setAuthorizationBaseUrl('https://71638791.ngrok.io/OAuth/Authorize') 
      .setTokenUrl('https://911ba796.ngrok.io/OAuth/Token')
      .setClientId('<CLIENT ID FOR PROJECT>')
      .setClientSecret('<CLIENT SECRET>')
      .setScope('https://www.googleapis.com/auth/gmail.metadata')
      .setCallbackFunction('authCallback')
      .setLock(LockService.getUserLock())
      .setCache(CacheService.getUserCache())
      .setPropertyStore(PropertiesService.getUserProperties());
}
```
which seems to work fine. When the authentication process is done on my server side I end up in my callback function (authCallback) which looks like this:
 ```javascript
function authCallback(callbackRequest) {  
  var authorized = getOAuthService().handleCallback(callbackRequest);
  if (authorized) {
    return HtmlService.createHtmlOutput(
      'Success! <script>setTimeout(function() { top.window.close() }, 1);</script>');
  } else {
    return HtmlService.createHtmlOutput('Denied');
  }
}
```
So far so good, but I always get the error:
**Error: Token response not valid JSON: SyntaxError: Unexpected token: T (line 543, file "Service", project "OAuth2")**

Which may be perfectly reasonable; the JSON that ends up getting passed as the callbackRequest request parameter is a bit unwieldy. It looks like this:
```
{
  "parameter": {
    "code": "f3af879162e8423289efa08e192c5ec4011ff7b3496e4a3f86ae35580ced2a38",
    "state": "ADEpC8xL-V6CzrQOSoC6sqOfAkvyR0FpE2C8P_IBh-JUVEskUtnocQllyYLKHsSKmJ3YkLNZjyl_9H07P03OdK3vIIvsgQ3Eth24ByjI4W-Lay4mGE_PJWtYa2_-G1wSR-0U4JBi9d7AxIT_X9xH7OwjQdoDEVq65MIzahmIb8xnKtBImByK8bKDz4WY_3H-qf2Om5S-LkX4evSk-bbzUhfUSQzvngOYrUInBButIRGbDSWaCr4lST3O_pzRad5xDaDtb3gH45dqH7hjXMXtsEOMSitR4A-wHrNLlQEKNk7O_v77lFVtKCbyTWsZD5zqiBUi10PCf12PuF1MmEoIVLPL0XmjbNpEpg",
    "serviceName": "CityViewIntegrationService"
  },
  "contextPath": "",
  "contentLength": -1,
  "queryString": "code=f3af879162e8423289efa08e192c5ec4011ff7b3496e4a3f86ae35580ced2a38&state=ADEpC8xL-V6CzrQOSoC6sqOfAkvyR0FpE2C8P_IBh-JUVEskUtnocQllyYLKHsSKmJ3YkLNZjyl_9H07P03OdK3vIIvsgQ3Eth24ByjI4W-Lay4mGE_PJWtYa2_-G1wSR-0U4JBi9d7AxIT_X9xH7OwjQdoDEVq65MIzahmIb8xnKtBImByK8bKDz4WY_3H-qf2Om5S-LkX4evSk-bbzUhfUSQzvngOYrUInBButIRGbDSWaCr4lST3O_pzRad5xDaDtb3gH45dqH7hjXMXtsEOMSitR4A-wHrNLlQEKNk7O_v77lFVtKCbyTWsZD5zqiBUi10PCf12PuF1MmEoIVLPL0XmjbNpEpg",
  "parameters": {
    "code": [
      "f3af879162e8423289efa08e192c5ec4011ff7b3496e4a3f86ae35580ced2a38"
    ],
    "state": [
      "ADEpC8xL-V6CzrQOSoC6sqOfAkvyR0FpE2C8P_IBh-JUVEskUtnocQllyYLKHsSKmJ3YkLNZjyl_9H07P03OdK3vIIvsgQ3Eth24ByjI4W-Lay4mGE_PJWtYa2_-G1wSR-0U4JBi9d7AxIT_X9xH7OwjQdoDEVq65MIzahmIb8xnKtBImByK8bKDz4WY_3H-qf2Om5S-LkX4evSk-bbzUhfUSQzvngOYrUInBButIRGbDSWaCr4lST3O_pzRad5xDaDtb3gH45dqH7hjXMXtsEOMSitR4A-wHrNLlQEKNk7O_v77lFVtKCbyTWsZD5zqiBUi10PCf12PuF1MmEoIVLPL0XmjbNpEpg"
    ],
    "serviceName": "IntegrationService"
  }
}
```
I tried cutting out elements bit by bit until I was passing in 
```{"parameter":{"code":"d8a1211d314844cfb11eefd2cd2063369f743b67b6d140d7a2d010f50cb20d44"}}```

but I still ended up with the same "Unexpected Token" error. This makes me believe that I am likely missing elements that I should add before the AuthenticationTokenCreateContext  gets sent back to app script. 
Any idea what I missed? Apologies if I missed anything in the documentation.

**Comment by erickoledadevrel** [comment] 2019-06-05 12:58
So this error is being thrown by the code that parses the response from your access token endpoint:

https://github.com/gsuitedevs/apps-script-oauth2/blob/4f966522b36994b294826ebc55a3a6f9cadda775/src/Service.js#L540-L544

In your case that's the response from `https://911ba796.ngrok.io/OAuth/Token`. What you need to check is what response is that endpoint returning to Apps Script, and is it correctly formatted JSON. The response doesn't need to be JSON, but if you are using another format you need to specify that in your service configuration:

https://github.com/gsuitedevs/apps-script-oauth2#setting-the-token-format

**Comment by ShovelHand** [comment] 2019-06-05 16:21
Thanks, this did turn out to be an issue. I initially logged the JSON by calling stringify on the callbackResponse, and that validated in https://jsonformatter.org/, but the raw callback response that is not stringified does not, so I mislead myself.

**Comment by erickoledadevrel** [comment] 2019-06-05 16:45
Glad to hear you found the cause, closing this issue.

**Closed by erickoledadevrel** 2019-06-05 16:45 UTC
