### ISSUE TITLE
Too many redirects when attempting authorisation from the Gmail app 

### ISSUE THREAD

**Issue by patillades** [gsuitedevs/apps-script-oauth2#92] opened 2017-11-15 14:27 UTC
I'm working on a gmail add-on with the following code:

```js
    function getGoogleService() {
      return OAuth2.createService('google')
        .setAuthorizationBaseUrl('https://accounts.google.com/o/oauth2/auth')
        .setTokenUrl('https://accounts.google.com/o/oauth2/token')
        .setClientId('...')
        .setClientSecret('...')
        .setCallbackFunction('authCallback')
        .setPropertyStore(PropertiesService.getUserProperties())
        .setScope('profile email')
        .setParam('login_hint', Session.getActiveUser().getEmail())
    }

    function authCallback(callbackRequest) {
      var authorized = getGoogleService().handleCallback(callbackRequest);
  
      if (authorized) {
        return HtmlService.createHtmlOutput(
          'Success! <script>setTimeout(function() { top.window.close() }, 1);</script>'
        );
      } else {
        return HtmlService.createHtmlOutput('Denied');
      }
    }
```

I've taken it from `README.md` and it works when the authorisation is done from gmail's desktop web. But when attempting the same from the android Gmail app, the browser shows a TOO_MANY_REDIRECTS error on the `https://script.google.com/macros/d/{SCRIPT ID}/usercallback` URL, as can be seen on the screenshot.

![screenshot_20171115-125749](https://user-images.githubusercontent.com/8511199/32840916-4da70bec-ca19-11e7-8de0-c3908736980e.png)

If I log in first through the web, the add-on works fine on the app. I've tried trello and asana add-ons and the same happens with them, so the issue might not be related to this library.

**Comment by erickoledadevrel** [comment] 2018-05-18 14:48
I tried to replicate this with the Trello and Asana add-ons, but both worked correctly on my phone. I've seen issues similar to this when using multi-login, are by chance logged into more than one Google account on your phone's browser?

**Comment by AdamHickey00** [comment] 2018-05-22 17:51
I've not been able to duplicate this, but one of our clients is experiencing this issue.

I will follow up with any further details.

**Comment by AdamHickey00** [comment] 2018-05-23 14:08
Apparently, it is a known issue when users are logged into multiple accounts and the Gmail team is actively working on it.

**Comment by hariiprasath** [comment] 2018-06-12 20:41
> Apparently, it is a known issue when users are logged into multiple accounts and the Gmail team is actively working on it.

So I just tried logging in with incognito mode and it worked like a charm!

**Comment by erickoledadevrel** [comment] 2018-06-13 00:36
Looks to be a problem outside of this library, closing.

**Comment by erickoledadevrel** [comment] 2018-08-09 15:35
@wittekm - Are you able to repro this on the Gmail desktop web app as well? The original report was about the Android app.

**Comment by wittekm** [comment] 2018-08-09 16:40
> Gmail desktop web app

Just to clarify, you just mean in-browser `gmail.com`? If so: Yep! And it's reproducible in both Firefox and Chrome.

I've been in contact with an engineer on CardService (the declarative UI part of Gmail apps script addons) who said:
> Thanks for sharing this with us. For the error with too many redirects, it is caused by multi login and I can contact the responsible team for ETA.

**Comment by wittekm** [comment] 2018-08-15 20:33
(Also, here's a view of the redirect loop, if it helps.) ![image](https://user-images.githubusercontent.com/578530/44171699-c2934900-a08f-11e8-84e4-6cf6e1b6ca24.png)

**Comment by cameron-gq** [comment] 2018-09-18 17:49
We are seeing this as well and are able to reproduce on Gmail desktop web.  

Sign in to multiple Gmail accounts in the same Chrome browser/profile.  Attempt authorization with the second Gmail account and it gives the redirect error.

<img width="1273" alt="screen shot 2018-09-18 at 11 48 30 am" src="https://user-images.githubusercontent.com/28717075/45706197-da4f6880-bb38-11e8-8a95-e6bb2c99f597.png">

**Comment by ksben** [comment] 2018-10-28 14:57
Hello Eric,
I am using your library with users and when they attempt to log-in with school google account on their personal laptop's or personal desktop browsers.   They seem to get caught in a google authentication loop.  One user this morning said when he logs-in using incognito mode, the loop disappears and authentication works.

Is there an approved workaround based on your OAuth2 webApp example for gmail users not wishing to use incognito browsers?

**Comment by erickoledadevrel** [comment] 2018-11-01 20:01
Sorry for the slow response here. I tried to repro this today but I am having some trouble even getting past the Google auth process when two gmail.com accounts are logged in at the same time.

Regardless, it seems like the core problem lies within the `/usercallback` endpoint that the library relies on, which is part of the core Apps Script codebase. Looking at some internal notes, a change may have gone out in September that has replaced the infinite redirect with an error page. Is anyone seeing that?

The engineering team is actively working to better support multi-login for Apps Script, specifically to address this use case. Unfortunately I can't give you an estimate as to when that will be in production.

**Comment by ksben** [comment] 2018-11-01 21:06
Hi Eric. Thank you for your response. I haven’t attempted it, but could the library sign out any google users signed in that browser and then attempt to authenticate the user. Would that cause browser issues for the user who prefers to stayed signed in?  I did see a scenario where there was an authentication loop up until the user signed out of his other google accounts.

**Comment by erickoledadevrel** [comment] 2018-11-13 17:58
There is an issue tracking this problem on the Gmail Add-ons public issue tracker:

https://issuetracker.google.com/69396852

Please star that issue to get updates and indicate that it is important to you.

**Comment by erickoledadevrel** [comment] 2019-01-08 16:56
Closing this GitHub issue, since the problem lies in the underlying Gmail and Apps Script implementation. Please follow the bug mentioned above for updates.

**Closed by erickoledadevrel** 2019-01-08 16:56 UTC

**Comment by waqarcf** [comment] 2026-03-28 15:53
I changed the authorizationBaseUrl and ToeknURL as below and it worked.

```
.setAuthorizationBaseUrl('https://accounts.google.com/o/oauth2/v2/auth')
.setTokenUrl('https://oauth2.googleapis.com/token')
```
